name: event
description: "aplicación"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Estado y gestión
  provider: ^6.1.1

  # HTTP y API
  http: ^1.2.0
  dio: ^5.4.0

  # Almacenamiento local
  shared_preferences: ^2.2.2

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1

  # Utilidades
  intl: ^0.19.0

  # Iconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
